name       : dustrac
version    : 1.11.0
release    : 1
source     :
    - https://github.com/juzzlin/DustRacing2D/archive/1.11.0.tar.gz : 48512ce979d4c4945dd6b9b4832da88619113477a53f0b7e7edee832f5a582ec
license    : GPL-3.0
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(Qt5Core)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake
    %cmake -DReleaseBuild=1 \
           -DCMAKE_INSTALL_PREFIX=/usr \
           -DDEFAULT_DATA_PATH_BASE=share/dustrac .
build      : |
    %make
install    : |
    %make_install
