name       : dustrac
version    : 2.1.1
release    : 13
source     :
    - https://github.com/juzzlin/DustRacing2D/archive/2.1.1.tar.gz : e028a49ad427fb0527b2bf05dad72404cc2d20883da1d330cb1319246bdc423a
homepage   : http://juzzlin.github.io/DustRacing2D
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing 2D (Dustrac) is a tile-based, cross-platform 2D racing game written in Qt (C++) and OpenGL. Dust Racing 2D comes with a Qt-based level editor for easy level creation. A separate engine, MiniCore, is used for physics modeling.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake
    %cmake -DReleaseBuild=1 \
           -DDEFAULT_DATA_PATH_BASE=share/dustrac .
build      : |
    %make
install    : |
    %make_install
