name       : dustrac
version    : 2.1.0
release    : 12
source     :
    - https://github.com/juzzlin/DustRacing2D/archive/2.1.0.tar.gz : ec910af1b169e4b17f4f0a523ba310870ba0234bfe5d248d5dce806feb54c3e8
homepage   : http://juzzlin.github.io/DustRacing2D
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake
    %cmake -DReleaseBuild=1 \
           -DDEFAULT_DATA_PATH_BASE=share/dustrac .
build      : |
    %make
install    : |
    %make_install
