name       : dustrac
version    : 2.0.3
release    : 7
source     :
    - https://github.com/juzzlin/DustRacing2D/archive/2.0.3.tar.gz : cbf73fc1c446d4068222c51d7fd67bd90dcce2651ba2aa2ae8aecb2dc8ee0873
homepage   : http://juzzlin.github.io/DustRacing2D
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake
    %cmake -DReleaseBuild=1 \
           -DDEFAULT_DATA_PATH_BASE=share/dustrac .
build      : |
    %make
install    : |
    %make_install
