name       : dustrac
version    : 1.12.0
release    : 3
source     :
    - https://github.com/juzzlin/DustRacing2D/releases/download/1.12.0/dustrac-1.12.0.tar.gz : e0224eb9d5cbf787311daeb8a1769917e0aed9c1cf2140f3e071dd5a28d3dcbf
license    : GPL-3.0
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(Qt5Help)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake
    %cmake -DReleaseBuild=1 \
           -DDEFAULT_DATA_PATH_BASE=share/dustrac .
build      : |
    %make
install    : |
    %make_install
