name       : dustrac
version    : 2.0.4
release    : 9
source     :
    - https://github.com/juzzlin/DustRacing2D/archive/2.0.4.tar.gz : 660cac182af17eae7c60955b37e95714a1d8eff9c5515eb52a1b12cf4f7be155
homepage   : http://juzzlin.github.io/DustRacing2D
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake
    %cmake -DReleaseBuild=1 \
           -DDEFAULT_DATA_PATH_BASE=share/dustrac .
build      : |
    %make
install    : |
    %make_install
